server:
  error:
    include-stacktrace: ON_PARAM

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true